//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerExchangeVehicle
    {
        public int CustomerExchangeVehicleID { get; set; }
        public int CustomerEnquiryID { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> mfgdate { get; set; }
        public string EngineCondition { get; set; }
        public string OutlookCondition { get; set; }
        public int CustomerRate { get; set; }
        public string BrokerName1 { get; set; }
        public Nullable<int> Mobileno1 { get; set; }
        public Nullable<int> Rate1 { get; set; }
        public Nullable<int> DifferenceAmount1 { get; set; }
        public string BrokerName2 { get; set; }
        public Nullable<int> Mobileno2 { get; set; }
        public Nullable<int> Rate2 { get; set; }
        public Nullable<int> DifferenceAmount2 { get; set; }
        public string ExchangeRemark { get; set; }
        public Nullable<int> FinalAmount { get; set; }
        public int Createdby { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
    
        public virtual CustomerEnquiry CustomerEnquiry { get; set; }
    }
}
