//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceMargin
    {
        public int InvoiceMarginID { get; set; }
        public int InvoiceID { get; set; }
        public string InvoiceType { get; set; }
        public int VehicleBookingID { get; set; }
        public int MarginTypeID { get; set; }
        public Nullable<int> MarginAmount { get; set; }
        public Nullable<int> ActualAmount { get; set; }
        public Nullable<int> ManualAmount { get; set; }
        public Nullable<int> MarginID { get; set; }
        public string Remarks { get; set; }
        public bool IsReceived { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public bool IsCash { get; set; }
        public string ChequeOrBankTranNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
    }
}
