//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePartsInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SparePartsInventory()
        {
            this.SparePartsBookingAllotments = new HashSet<SparePartsBookingAllotment>();
            this.SparePartsInventoryStatus = new HashSet<SparePartsInventoryStatu>();
        }
    
        public int SparePartsInventoryID { get; set; }
        public int SparePartsInfoID { get; set; }
        public string IdentificationNo { get; set; }
        public string OtherDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public Nullable<bool> IsMarginPrice { get; set; }
        public Nullable<bool> Is50PercentMarginPrice { get; set; }
        public Nullable<bool> Is70PercentMarginPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SparePartsBookingAllotment> SparePartsBookingAllotments { get; set; }
        public virtual SparePartsInfo SparePartsInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SparePartsInventoryStatu> SparePartsInventoryStatus { get; set; }
    }
}
