//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePartsBookingAllotment
    {
        public int SparePartsBookingAllotmentID { get; set; }
        public int VehicleBookingID { get; set; }
        public int SparePartsInventoryID { get; set; }
        public int Createdby { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
    
        public virtual SparePartsInventory SparePartsInventory { get; set; }
        public virtual VehicleBooking VehicleBooking { get; set; }
    }
}
