//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleBooking()
        {
            this.OtherBookingAllotments = new HashSet<OtherBookingAllotment>();
            this.SparePartsBookingAllotments = new HashSet<SparePartsBookingAllotment>();
            this.VehicleBookingFinanceAllotments = new HashSet<VehicleBookingFinanceAllotment>();
            this.VehicleBookingRTOAllotments = new HashSet<VehicleBookingRTOAllotment>();
            this.VehicleBookingAllotments = new HashSet<VehicleBookingAllotment>();
            this.VehicleBookingFollowUps = new HashSet<VehicleBookingFollowUp>();
            this.VehicleBookingInsuranceAllotments = new HashSet<VehicleBookingInsuranceAllotment>();
        }
    
        public int VehicleBookingID { get; set; }
        public Nullable<int> VehicleEnquiryID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> CommittedDays { get; set; }
        public Nullable<System.DateTime> CommittedDate { get; set; }
        public int ModelID { get; set; }
        public string Color1 { get; set; }
        public string Color2 { get; set; }
        public string Color3 { get; set; }
        public string CustomerRemark { get; set; }
        public string Referenceby { get; set; }
        public int SalesExecutiveID { get; set; }
        public bool isCash { get; set; }
        public Nullable<int> AdvanceAmount { get; set; }
        public Nullable<bool> AdvanceAmountModeBit { get; set; }
        public Nullable<int> AdvanceChequeno { get; set; }
        public Nullable<int> FinancierID { get; set; }
        public string FinancierRemark { get; set; }
        public Nullable<bool> ReadytoDelivery { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string ClosingRemark { get; set; }
        public int Createdby { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherBookingAllotment> OtherBookingAllotments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SparePartsBookingAllotment> SparePartsBookingAllotments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleBookingFinanceAllotment> VehicleBookingFinanceAllotments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleBookingRTOAllotment> VehicleBookingRTOAllotments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleBookingAllotment> VehicleBookingAllotments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleBookingFollowUp> VehicleBookingFollowUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleBookingInsuranceAllotment> VehicleBookingInsuranceAllotments { get; set; }
    }
}
