//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleBookingInsuranceAllotment
    {
        public int VehicleBookingInsuranceAllotmentID { get; set; }
        public int VehicleBookingID { get; set; }
        public bool InsuranceByDealer { get; set; }
        public int InsuranceInfoID { get; set; }
        public Nullable<int> CoverNoteNo { get; set; }
        public Nullable<int> PolicyNo { get; set; }
        public Nullable<int> PolicyAmount { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> PolicyDeliveredTo { get; set; }
        public Nullable<System.DateTime> PolicyDeliveredDate { get; set; }
        public Nullable<int> ContactNo { get; set; }
        public int Createdby { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
    
        public virtual InsuranceInfo InsuranceInfo { get; set; }
        public virtual VehicleBooking VehicleBooking { get; set; }
    }
}
