//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleInventoryStatu
    {
        public int VehicleInventoryStatusID { get; set; }
        public int VehicleInventoryID { get; set; }
        public int VehicleInventoryStatusTypeID { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
    
        public virtual VehicleInventory VehicleInventory { get; set; }
        public virtual VehicleInventoryStatusType VehicleInventoryStatusType { get; set; }
    }
}
