//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleBookingRTOAllotment
    {
        public int VehicleBookingRTOAllotmentID { get; set; }
        public int VehicleBookingID { get; set; }
        public int RTOInfoID { get; set; }
        public string TempRegNo { get; set; }
        public string RegNo { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<int> Amount { get; set; }
        public string AgentName { get; set; }
        public string RCBookNo { get; set; }
        public Nullable<int> RCDeliveredTo { get; set; }
        public Nullable<System.DateTime> RCDeliveredDate { get; set; }
        public string Remark { get; set; }
        public int Createdby { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
    
        public virtual VehicleBooking VehicleBooking { get; set; }
        public virtual RTOInfo RTOInfo { get; set; }
    }
}
