//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleInfo()
        {
            this.VehicleInventories = new HashSet<VehicleInventory>();
        }
    
        public int VehicleInfoID { get; set; }
        public int VehicleTypeID { get; set; }
        public string ModelCode { get; set; }
        public string ModelName { get; set; }
        public int ExShowRoomPrice { get; set; }
        public int LT_RT_OtherExp { get; set; }
        public int InsurancePrice { get; set; }
        public int OnRoadPrice { get; set; }
        public int MarginPrice { get; set; }
        public int C50PercentMargin { get; set; }
        public int C70PercentMargin { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleInventory> VehicleInventories { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
}
