//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MM.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleBookingFollowUp
    {
        public int VehicleBookingFollowUpID { get; set; }
        public int VehicleBookingID { get; set; }
        public int CustomerID { get; set; }
        public string Description { get; set; }
        public System.DateTime FollowupDate { get; set; }
        public bool isActive { get; set; }
        public int Createdby { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Modifiedby { get; set; }
    
        public virtual VehicleBooking VehicleBooking { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
