Delete from BankAccountType
Delete from BankAccountTransaction
Delete from CashTransaction
Delete from dbo.CustomerEnquiryFollowUp
Delete from dbo.CustomerExchangeVehicle
Delete from dbo.CustomerEnquiry
Delete from dbo.Customer
Delete from dbo.ExpenseTransaction
Delete from Expenses
Delete from dbo.VehicleBookingFinanceAllotment
--Delete from dbo.FinanceInfo
Delete from dbo.VehicleBookingInsuranceAllotment
--Delete from dbo.InsuranceInfo
Delete from dbo.VehicleBookingRTOAllotment
--Delete from dbo.RTOInfo
--Delete from dbo.EmployeeLoginDetails
--Delete from dbo.EmployeeRole
--Delete from dbo.Employees
