Insert into dbo.MarginType Values('VehicleIAMargin','VehicleInventoryID',GETDATE(), 1, null,null)
Insert into dbo.MarginType Values('BankMargin','FinancierInfoId',GETDATE(), 1, null,null)
Insert into dbo.MarginType Values('WarrantyMargin','VehicleInventoryID',GETDATE(), 1, null,null)
Insert into dbo.MarginType Values('ExtraFittingMargin','SparePartsInventoryID',GETDATE(), 1, null,null)
Insert into dbo.MarginType Values('DiscountMargin','VehicleBookingId',GETDATE(), 1, null,null)