
DBCC CHECKIDENT ('SparePartsType', RESEED, 20);
SET Identity_Insert SparePartsType ON
Go
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(21,' END GRIP ASSY SILVER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(22,'AIR SHROUND', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(23,'ASSIST GRIP ASSY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(24,'AXLE WHEEL FRONT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(25,'AXLE WHEEL RR', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(26,'BAND 2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(27,'BAR TENSON', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(28,'BEARING', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(29,'BODY ASSY H.LIGHT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(30,'BODY CAP', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(31,'BOLT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(32,'BOLT HEX SOCKET BUTTON', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(33,'BOLT FLANGE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(34,'BOLT HEX.SOCKET BUTTON', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(35,'BOSS CLUTCH', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(36,'BOSS CLUTCH', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(37,'BRACKET FOOTREST 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(38,'BRACKET LICENSE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(39,'BRAKE PAD KIT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(40,'BRAKE SHOE SET-REAR/FRONT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(41,'BREAKE PAD KIT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(42,'BULP FLASHER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(43,'BULP HEADLIGHT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(44,'CABLE BREAK ', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(45,'CABLE CLUTCH', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(46,'CABLE STARTER 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(47,'CABLE THROTTLE 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(48,'CABLE THROTLE 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(49,'CABLE THROTTLE 2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(50,'CABLE THROTTLE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(51,'CAM COVER O RING', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(52,'CAP', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(53,'CHAIN- 118 LINKS', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(54,'CHAIN SPROCKET FZ V2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(55,'CHAIN SPROCKET KIT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(56,'CLIP', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(57,'CLUTCH CABLE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(58,'CLUTCH LEVER ', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(59,'CLUTCH ONEWAY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(60,'COLLAR', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(61,'COVER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(62,'COVER 7 -VRC1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(63,'COVER FOOT REAR', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(64,'COVER FOOT REST', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(65,'COVER GUIDE (SEAT 2)', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(66,'COVER KICK LEVER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(67,'COVER REAR FOOTREST', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(68,'COVER STARTER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(69,'COVER TAIL1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(70,'COVER UPPER1- YB-21C2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(71,'COVER OIL ELEMENT -SILVER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(72,'COVER OUTER 1 YB BLACK', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(73,'COVER SEAT LOCK', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(74,'COVER UPPER 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(75,'COVER.SIDE 6 -VRC1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(76,'CYLINDER HEAD GASKET', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(77,'CYLINDER KIT MASTER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(78,'DAMPER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(79,'DAMPER PLATE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(80,'DANGER LIGHT BULP', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(81,'DIMMER SWITCH COMP', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(82,'DUCT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(83,'ELEMENT 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(84,'ELEMENT 2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(85,'ELEMENT ASSY  AIR CLEANER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(86,'ELEMENT ASSY  AIR CLEANER ', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(87,'ELEMENT ASSY AIR CLEANER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(88,'END  GRIP', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(89,'ENGINE OIL SEAL KIT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(90,'FAN', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(91,'FILTER ELEMENT 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(92,'FLASHER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(93,'FLASHER LIGHT ASSY 2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(94,'FLASHER LIGHT ASSY1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(95,'FLASHER RELAY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(96,'FLASHER RELAY ASSY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(97,'FOOTREST', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(98,'FOOTREST ', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(99,'FOOTREST LH', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(100,'FOOTREST -LH', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(101,'FOOTREST RH', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(102,'FOOTREST REAR 2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(103,'FOOTREST-RH', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(104,'FORK TAP END PUSH', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(105,'FR.FLASHER LIGHT ', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(106,'FR.REFLECTER.ASSY.1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(107,'FRONT BREAKE LEVER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(108,'FRONT FLASHER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(109,'FRONT FLASHER LIGHT ASSY 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(110,'FRONT FLASHER LIGHT ASSY 2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(111,'FRONT FLASHER LT ASSY LH', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(112,'FRONT FLASHER LT ASSY RH', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(113,'FRONT LIGHT ASSY 2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(114,'FRONT MURGUARD  SZ.RR', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(115,'FRONT MURGUARD FASCINO', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(116,'FRONT MURGUARD R15', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(117,'FRONT STOP SWITCH ASSY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(118,'FUEL COCK', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(119,'FUEL COCK ASSY 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(120,'FUEL PIPE WITH CLIPS', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(121,'GASKET', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(122,'GASKET  CRANKCASE COVER 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(123,'GASKET  CYLINDER [5YY]', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(124,'GASKET COVER CC2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(125,'GASKET CY.HEAD', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(126,'GASKET CYLINDER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(127,'GASKET CYLINDER [5YY]', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(128,'GASKET CYLINDER HEAD 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(129,'GASKET ELEMENT COVER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(130,'GASKET EXHAUST1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(131,'GASKET C.CASE 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(132,'GASKET CRANKCASE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(133,'GASKET CRANKCASE COVER 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(134,'GASKET CRANKCASE COVER 2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(135,'GASKET CRANKCASE COVER2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(136,'GASKET CYLINDER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(137,'GASKET CYLINDER HEAD1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(138,'GASKET EXHAUST PIPE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(139,'GEAR UNIT ASSY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(140,'GEAR WHEEL', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(141,'GRIP -2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(142,'GRIP ASSY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(143,'GROMMET', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(144,'GUIDE STOPPER 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(145,'GUIDE STOPPER 2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(146,'HANDLE BAR', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(147,'HAZARD FLASHER SWITCH', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(148,'HEX BOLT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(149,'HOLDER WIRE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(150,'HOOK1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(151,'HORN', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(152,'HOSE BEND 2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(153,'IGNITION COIL ASSY WINGS', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(154,'INDICATOR BULB ', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(155,'INSULATER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(156,'KICK OIL SEAL IN RH COVER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(157,'KICK SEAL IN RH COVER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(158,'KIT PUSH LEVER ASSY FZ SZ', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(159,'LENS LEVEL GAUGE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(160,'LENS LEVER GAUGE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(161,'LEVER 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(162,'LEVER 2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(163,'LIGHTING SWITCH', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(164,'LINK MAIN STAND', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(165,'MAIN STAND RAY Z', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(166,'MAIN SWITCH WITH ASSY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(167,'MASK COVELING PEACE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(168,'MIRROR ASSY RH', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(169,'MOLE 1- CM6', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(170,'NEUTRAL SWITCH ASSY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(171,'NUT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(172,'NUT BRAKE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(173,'NUT SPRING', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(174,'O RING', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(175,'O RING ROCKER COVER NUT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(176,'OIL SEAL', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(177,'OIL SEAL DRIVE SPROCKET', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(178,'OIL SEAL IN RH COVER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(179,'OIL SEAL PUSH LEVER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(180,'OIL SEAL -TFF', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(181,'OIL VALVE STEM', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(182,'PEDAL BRAKE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(183,'PEDAL SHIFT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(184,'PIN PISTON', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(185,'PIN WITH HOLE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(186,'PIPE  OIL TANK BREATHER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(187,'PIPE FUEL WITH TWO CLIPS', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(188,'PIPE OIL TANK BREATHER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(189,'PLATE PRESSURE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(190,'PLATE FRICTION', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(191,'PLATE PRESURE1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(192,'PLUG STRAIGHT SCREW', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(193,'PLUG STRAIGHT SCREW ', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(194,'PLUG DRAIN', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(195,'PROTECTER MUFLER 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(196,'PROTECTER MUFLER 2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(197,'PROTECTER MUFLER 5KA3', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(198,'PUSH LEVER COMP', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(199,'RACE BRG KIT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(200,'REAR FLASHER LIGHT ASSY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(201,'REAR FLASHER LIGHT ASSY 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(202,'REAR FLASHER LIGHT ASSY 2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(203,'REAR FOOTREST FZ V2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(204,'REAR VIEW MIRROR A', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(205,'REAR VIEW MIRROR ASSY [LH]', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(206,'REAR VIEW MIRROR ASSY [RH]', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(207,'REAR VIEW MIRROR ASSY 1[ RH]', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(208,'REARFLASHER LIGHT ASSY 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(209,'REAT AINER BALL BEARING', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(210,'RELAY ASSY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(211,'RIM HEAD LIGHT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(212,'SCOOP GUIDE AIR 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(213,'SCREW VALVE ADJUSTER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(214,'SCREW PAN HEAD', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(215,'SCREW TAPPING', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(216,'SEAL GUARD', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(217,'SEAL VALVE STEM', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(218,'SEAL AIR DUCT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(219,'SEAL DUST', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(220,'SEAT COVER SPORTS', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(221,'SHIFT PEDAL ASSY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(222,'SHIFT SHAFT ASSY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(223,'SHIFT SHAFT ASSY-35B1/2', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(224,'SPARK PLUG', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(225,'SPARK PLUG TERMINAL', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(226,'SPEEDO GEAR KIT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(227,'SPEEDOMETER CABLE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(228,'SPEEDOMETER CABLE ASSY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(229,'SPRING', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(230,'SPRING COMPRESSION', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(231,'SPRING FRONT FORK', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(232,'SPRING TENSION ( 5YY)', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(233,'SPRING TENSION (5YY)', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(234,'SPRING TORSION', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(235,'SPRING RETURN', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(236,'SPRING TENSION', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(237,'SPROCKET DRIVE (14T)', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(238,'SPROCKET DRIVE (15T)', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(239,'SPROCKET DRIVEN', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(240,'SPROCKET DRIVEN [45T]', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(241,'STAND MAIN', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(242,'STAND SIDE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(243,'STARTER RELAY ASSY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(244,'STARTER SWITCH ASSY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(245,'STARTOR ASSY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(246,'STAY  LOCK', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(247,'STAY ASST-1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(248,'STAY PLATE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(249,'STOP SWITCH ASSY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(250,'STOPPER EXHAUST PIPE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(251,'STRAINER OIL', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(252,'SWITCH', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(253,'SWITCH HANDLE-5', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(254,'TENSOR ASSY CAM CHAIN', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(255,'VALVE - 1 (INLET)', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(256,'VALVE  EXHAUST', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(257,'VALVE 2 ( EXHAUST)', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(258,'VALVE-1 INTAKE', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(259,'WHEEL RATCHIET', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(260,'WINDSHELD', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(261,'WINSHELD YBR 110', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(262,'WIRE BRAKE ', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(263,'WIRE BREAK', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(264,'WIRE CLUTCH', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(265,'WIRE PLUS LEAD', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(266,'WIRE STARTER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(267,'WIRE THROTTLE 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(268,'WIRE  MINUS HEAD', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(269,'WIRE PLUS LEAD', GetDATE(), 1, null, null)

Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(270,'KIT KICK STARTER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(271,'SHOCK ABSORBER ASSY,REAR', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(272,'PRIMARY DRIVEN GEAR COMP', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(273,'CAP,CLEANER CASE 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(274,'HUB FRONT', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(275,'CRANKSHAFT ASSY', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(276,'TANK SIDE COVER 1 YB[BLACK]', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(277,'PROTECTER MUFFLER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(278,'PROTECTER MUFFLER 1', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(279,'HEADLIGHT COVELING  SZ.RR', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(280,'HEADLIGHT COVELING  SS 125', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(281,'HEADLIGHT COVELING FAZER', GetDATE(), 1, null, null)
Insert into SparePartsType (SparePartsTypeID, Description, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) Values(282,'HEADLIGHT DHOOM SS125', GetDATE(), 1, null, null)



Go
SET Identity_Insert SparePartsType OFF